# fly.toml app configuration file generated for pcl-pinecone-cohere-connector on 2024-01-21T17:43:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pcl-pinecone-cohere-connector"
primary_region = "ewr"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
